### ISSUE TITLE
[Enhancement] Clicking & Expand capability for SLI value graph

### ISSUE THREAD

**Issue by jayakody** [runwhen-contrib/runwhen-beta-issues#2]
**Observation** 
It would be good if a user is able to click on the "SLI Values" graph and be able to get expanded and more granular views of the metric graph. The use case I wanted to see was when my values started to cross the thresholds, i.e., the exact dates. It was somewhat hard to figure that out.  The default dropdowns (1hour/7days/30 days) didn't help that much. 

**Current Outcome** 

![Screen Shot 2022-08-16 at 10 23 49 AM](https://user-images.githubusercontent.com/6126932/184942991-5c39e3e2-191a-49b7-8dfc-a516d252f968.png)

**Desired Outcome**

**Comment by more-dinner** [comment]
We owe a reply.

Tracking internal conversation in runwhen-core #256 re: migrating off Chartist library rather than build this on top of current lib.
